#!/usr/bin/env bash
set -euo pipefail

echo "🚀 Running postCreate.sh..."

# Helper functions
has_cmd() { command -v "$1" >/dev/null 2>&1; }

# -------- detect package manager ----------
PKG_CMD=""
if has_cmd apk; then
  PKG_CMD="apk"
elif has_cmd apt-get; then
  PKG_CMD="apt"
elif has_cmd dnf; then
  PKG_CMD="dnf"
elif has_cmd yum; then
  PKG_CMD="yum"
elif has_cmd pacman; then
  PKG_CMD="pacman"
elif has_cmd brew; then
  PKG_CMD="brew"
else
  PKG_CMD=""
fi

install_sl_apk() {
  echo "→ Using apk to install sl"
  sudo apk update
  sudo apk add --no-cache sl
}

install_sl_apt() {
  echo "→ Using apt-get to install sl"
  sudo apt-get update
  sudo apt-get install -y sl
}

install_sl_dnf() {
  echo "→ Using dnf to install sl"
  sudo dnf install -y sl
}

install_sl_yum() {
  echo "→ Using yum to install sl"
  sudo yum install -y sl
}

install_sl_pacman() {
  echo "→ Using pacman to install sl"
  sudo pacman -Sy --noconfirm sl
}

install_sl_brew() {
  echo "→ Using Homebrew to install sl"
  brew update
  brew install sl
}

# ---------- install sl ----------
case "$PKG_CMD" in
  apk) install_sl_apk ;;
  apt) install_sl_apt ;;
  dnf) install_sl_dnf ;;
  yum) install_sl_yum ;;
  pacman) install_sl_pacman ;;
  brew) install_sl_brew ;;
  "")
    echo "⚠️  No supported package manager detected. Please install 'sl' manually."
    exit 0
    ;;
esac

# verify installation
if ! has_cmd sl; then
  echo "⚠️  'sl' was not found on PATH after installation. Attempting common locations..."
  # try common locations
  for p in /usr/games/sl /usr/bin/sl /usr/local/bin/sl; do
    if [ -x "$p" ]; then
      echo "→ Found sl at $p"
      SL_BIN="$p"
      break
    fi
  done
else
  SL_BIN="$(command -v sl)"
  echo "✓ sl installed at $SL_BIN"
fi

# --------- add /usr/games to PATH if needed ----------
# Only add if sl is in /usr/games and PATH doesn't already contain it
if [ -n "${SL_BIN:-}" ] && [[ "$SL_BIN" == /usr/games/* ]]; then
  for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    # skip if file doesn't exist; but create if it does not and shell is bash/zsh? we will append only if needed
    if [ -f "$rc" ]; then
      if ! grep -Fq '/usr/games' "$rc"; then
        echo "export PATH=\"\$PATH:/usr/games\"" >> "$rc"
        echo "✓ Added /usr/games to PATH in $rc"
      else
        echo "→ /usr/games already in $rc"
      fi
    else
      # file doesn't exist: create with the export to be safe
      echo "export PATH=\"\$PATH:/usr/games\"" >> "$rc"
      echo "✓ Created $rc and added /usr/games to PATH"
    fi
  done
else
  echo "→ No PATH change required (sl not in /usr/games or already on PATH)."
fi

# --------- optional convenience: create .env.codespace ----------
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env.codespace"
STEP_FILE="$REPO_ROOT/.github/steps/4-use-codespace.md"
ISSUE_URL="${ISSUE_URL:-https://github.com/$(git remote get-url origin 2>/dev/null | sed -n 's/.*github.com[:\/]\(.*\)\.git/\1/p')/issues/1}"

cat > "$ENV_FILE" <<EOF
# Auto-generated by postCreate.sh
STEP_4_FILE=$STEP_FILE
ISSUE_URL=$ISSUE_URL
EOF
echo "✓ Wrote $ENV_FILE"

# --------- done ----------
echo "🎉 postCreate.sh completed!"
echo "You can test by running: sl"
